/*
 * Listenarr - Audiobook Management System
 * Copyright (C) 2024-2026 Listenarr Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
using Listenarr.Tests.Common;

namespace Listenarr.Tests.Features.Architecture;

[Trait("Name", "MigrationProvenanceArchitectureTests")]
[Trait("Category", "Architecture")]
public sealed class MigrationProvenanceArchitectureTests : BaseTests
{
    private static readonly string RepositoryRoot = TestUtils.FindRepositoryRoot();

    [Fact]
    public void PullRequestMigrations_KeepEfScaffoldingAsSourceOfTruth()
    {
        const string canaryMigrationFrontier = "20260621002226";
        var migrationsRoot = Path.Join(
            RepositoryRoot,
            "listenarr.infrastructure",
            "Persistence",
            "Migrations");
        var migrationMains = Directory.EnumerateFiles(
                migrationsRoot,
                "*.cs",
                SearchOption.TopDirectoryOnly)
            .Where(file =>
            {
                var name = Path.GetFileName(file);
                return name.Length > 15
                    && string.CompareOrdinal(name[..14], canaryMigrationFrontier) > 0
                    && char.IsDigit(name[0])
                    && !name.EndsWith(".Designer.cs", StringComparison.Ordinal);
            })
            .ToList();
        var violations = new List<string>();

        foreach (var main in migrationMains)
        {
            var source = File.ReadAllText(main);
            var relative = Normalize(Path.GetRelativePath(RepositoryRoot, main));
            if (source.Contains("migrationBuilder.Sql(", StringComparison.Ordinal)
                || source.Contains("suppressTransaction", StringComparison.Ordinal)
                || source.Contains("[Migration(", StringComparison.Ordinal)
                || source.Contains("[DbContext(", StringComparison.Ordinal))
            {
                violations.Add($"{relative}: contains hand-shaped migration operations or discovery metadata");
            }

            var designer = Path.ChangeExtension(main, ".Designer.cs");
            if (!File.Exists(designer)
                || !File.ReadAllText(designer)
                    .StartsWith("// <auto-generated />", StringComparison.Ordinal))
            {
                violations.Add($"{relative}: missing its EF-generated Designer metadata");
            }
        }

        violations.AddRange(Directory.EnumerateFiles(
                migrationsRoot,
                "*.TargetModelAccessor.cs",
                SearchOption.TopDirectoryOnly)
            .Select(file =>
                $"{Normalize(Path.GetRelativePath(RepositoryRoot, file))}: custom target-model accessor"));

        Assert.True(
            violations.Count == 0,
            "#717 migrations must remain direct EF scaffolds. Move data repair to explicit startup primitives instead:"
            + Environment.NewLine
            + string.Join(Environment.NewLine, violations));
    }

    private static string Normalize(string path) => path.Replace('\\', '/');
}
