// <auto-generated />
using Listenarr.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Listenarr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ListenArrDbContext))]
    [Migration("20260720122500_EnforceSingleDefaultRootFolder")]
    partial class EnforceSingleDefaultRootFolder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            AddLibraryDirectoryOwnership.BuildTargetModelForSuccessor(modelBuilder);

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.RootFolder", b =>
                {
                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("IX_RootFolders_SingleDefault")
                        .HasFilter("\"IsDefault\" = 1");
                });
#pragma warning restore 612, 618
        }
    }
}
