// <auto-generated />
using Listenarr.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Listenarr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ListenArrDbContext))]
    [Migration("20260715115000_AddAudiobookFileOwnershipIdentity")]
    partial class AddAudiobookFileOwnershipIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            HardenMoveExecutionAndScanHandoffs.BuildTargetModelForSuccessor(modelBuilder);

            modelBuilder.Entity("Listenarr.Domain.Audiobooks.AudiobookFile", b =>
                {
                    b.Property<string>("CanonicalPath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathCaseSensitivity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathCaseSensitivityMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathIdentityBoundary")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathIdentityLookupKey")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathIdentityReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathIdentityState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("PathIdentityVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathOwnershipKey")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathSyntax")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasIndex("PathIdentityLookupKey");

                    b.HasIndex("PathOwnershipKey")
                        .IsUnique()
                        .HasFilter("\"PathOwnershipKey\" IS NOT NULL");
                });
#pragma warning restore 612, 618
        }
    }
}
